# Generated by Django 5.1.1 on 2024-10-10 09:57

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='photo',
            field=models.ImageField(null=True, upload_to=shop.models.generic_path_to_save_photo),
        ),
    ]
